services:
  otp:
    image: opentripplanner/opentripplanner:2.5.0
    ports:
      - "8080:8080"
    volumes:
      - ./otp_data:/var/opentripplanner
    command: --load --serve
    environment:
      - JAVA_OPTS=-Xmx8g